server:
  port: 8080

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: anamustapha
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true